#!/usr/bin/env python
"""Render studies/README.md and papers/README.md from the registry.

These files are generated, never hand-edited: the layout plan requires the registry to
be the only source of study state. `--check` fails when a rendered file has drifted,
so CI can enforce that without a human remembering to regenerate.

Usage:
    python tools/render_indexes.py            # write
    python tools/render_indexes.py --check    # fail if stale
"""
from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
BANNER = "<!-- GENERATED by tools/render_indexes.py from studies/registry.yaml. Do not edit. -->"

STATE_MARK = {
    "released": "released", "active": "active", "stopped": "stopped",
    "blocked": "blocked", "contract_drifted": "contract-drifted",
    "superseded": "superseded", "protocol_candidate": "protocol candidate",
    "development_only": "development only", "invalidated": "invalidated",
}


def load():
    import yaml
    return yaml.safe_load((ROOT / "studies/registry.yaml").read_text())


def studies_index(reg) -> str:
    lines = [BANNER, "", "# Studies", "",
             "Normative source: [`studies/registry.yaml`](registry.yaml), validated by",
             "[`registry.schema.json`](registry.schema.json). Run `make check-registry`.", "",
             f"Registry `{reg['registry_id']}` last verified at "
             f"`{reg['last_verified']['git_revision']}` on {reg['last_verified']['date']}"
             f"{' (dirty tree)' if reg['last_verified']['dirty_tree'] else ''}.", "",
             "## State", "",
             "| Study | State | Evidence | Claims? | Contract | Verification |",
             "| --- | --- | --- | --- | --- | --- |"]
    for s in reg["studies"]:
        claims = "**yes**" if s["claim_authorization"] else "no"
        exp = s["expected_verification_status"].replace("_", " ")
        lines.append(
            f"| `{s['study_id']}` | {STATE_MARK.get(s['study_state'], s['study_state'])} "
            f"| {s['evidence_state'].replace('_', ' ')} | {claims} "
            f"| {s['contract_type'].replace('_', ' ')} | {exp} |"
        )

    lines += ["", "## Declared verification failures", "",
              "A historical lock is *expected* to fail against an evolved tree. Declaring that",
              "is how a real regression stops hiding behind a known one.", ""]
    any_fail = False
    for s in reg["studies"]:
        if s["expected_verification_status"] == "expected_fail":
            any_fail = True
            reason = " ".join((s.get("verification_failure_reason") or "").split())
            lines += [f"**`{s['study_id']}`** — `{s.get('verification_command')}`", "",
                      f"> {reason}", ""]
    if not any_fail:
        lines.append("_None._")

    lines += ["", "## Lineage", ""]
    for s in reg["studies"]:
        edges = []
        if s.get("predecessor"):
            edges.append(f"after `{s['predecessor']}`")
        if s.get("successor"):
            edges.append(f"before `{s['successor']}`")
        if s.get("supersedes"):
            edges.append("supersedes " + ", ".join(f"`{x}`" for x in s["supersedes"]))
        if s.get("consumes"):
            edges.append("consumes " + ", ".join(f"`{x}`" for x in s["consumes"]))
        if edges:
            lines.append(f"- `{s['study_id']}` — {'; '.join(edges)}")

    # Derive the approved set rather than asserting it. This line previously hardcoded "No
    # source is currently approved for publish_text", which went stale the moment one was --
    # a generated view must not carry a claim about the file it summarizes.
    approved = [s["study_id"] for s in reg["studies"]
                if s["distribution_state"] == "publish_text"]
    lines += ["", "## Distribution", "",
              "Every source's redistribution decision lives in",
              "[`benchmarks/registry/distribution.yaml`](../benchmarks/registry/distribution.yaml)."]
    if approved:
        lines += ["", "Approved for verbatim redistribution (`publish_text`):", ""]
        lines += [f"- `{a}`" for a in approved]
        lines += ["", "Not approved:", ""]
    else:
        lines += ["No source is currently approved for `publish_text`.", ""]
    for s in reg["studies"]:
        if s["distribution_state"] in ("unresolved", "local_only"):
            lines.append(f"- `{s['study_id']}` — {s['distribution_state'].replace('_', ' ')}")
    return "\n".join(lines) + "\n"


def papers_index(reg) -> str:
    lines = [BANNER, "", "# Publications", "",
             "Publication state comes from [`studies/registry.yaml`](../studies/registry.yaml);",
             "this file is a generated view. A document under `papers/` is not automatically",
             "current — the label below is authoritative.", "",
             "| Manuscript | Study | Publication state | Evidence tier |",
             "| --- | --- | --- | --- |"]
    for s in reg["studies"]:
        for path in s.get("manuscript_paths") or []:
            rel = path[len("papers/"):] if path.startswith("papers/") else f"../{path}"
            tier = " ".join(s["evidence_tier"].split())
            lines.append(
                f"| [`{path}`]({rel}) | `{s['study_id']}` "
                f"| {s['publication_state']} | {tier} |"
            )
    lines += ["", "## Editorial lifecycle", "",
              "- `unified-report/proposal.md` is a contract-consumed starting-type protocol",
              "  despite its generic filename; it stays at its current path.",
              "- `unified-report/review-2026-07-30.md` is the latest scientific review; "
              "`review.md` and",
              "  `review-2026-07-17.md` are the two earlier ones, kept as the applied-fix record. "
              "(This list",
              "  named `review.md` as the latest after a newer one had been added.)",
              "- Simplified editions are editorial derivatives, not separate studies.",
              "- Office `~$` lock files are not publication artifacts and are git-ignored.", ""]
    return "\n".join(lines) + "\n"


def _bullets(label, values, note=""):
    if not values:
        return []
    out = [f"**{label}**" + (f" — {note}" if note else "")]
    out += [f"- [`{v}`](" + "../" * 2 + f"{v})" for v in values]
    return out + [""]


def package_readme(study, reg) -> str:
    """One study's navigation page, rendered from the registry.

    A package is navigation, not a second home. For a lock-bound study it holds no copy
    of the code -- `artifacts/paper_a_sft_v2/LOCK.json` binds `experiments/` paths, so a
    copy would either break the lock or silently diverge from it. What the package adds
    is a single place per study that answers: what does it ask, what may it claim, where
    does its code, config, evidence and manuscript live, and how do I verify it.
    """
    sid = study["study_id"]
    claims = ("**This study authorizes claims.**" if study["claim_authorization"]
              else "**This study authorizes no claim.**")
    lines = [BANNER, "", f"# {study['title']}", "",
             f"`{sid}` · {STATE_MARK.get(study['study_state'], study['study_state'])}"
             f" · evidence: {study['evidence_state'].replace('_', ' ')}"
             f" · contract: {study['contract_type'].replace('_', ' ')}", "",
             "## Question", "", study["question"].strip(), "",
             "## Standing", "",
             claims + " " + study.get("evidence_tier", "").strip().capitalize() + ".", ""]

    if study.get("notes"):
        lines += [study["notes"].strip(), ""]

    lines += ["## Where things live", ""]
    lines += _bullets("Code", [study["code_root"]] if study.get("code_root") else [],
                      "authoritative location; not copied here")
    lines += _bullets("Config", study.get("config_paths", []))
    lines += _bullets("Protocol", study.get("protocol_paths", []))
    lines += _bullets("Evidence", study.get("artifact_paths", []))
    lines += _bullets("Manuscript", study.get("manuscript_paths", []))
    if study.get("environment_path"):
        lines += _bullets("Environment", [study["environment_path"]])

    exp = study["expected_verification_status"].replace("_", " ")
    lines += ["## Verify", "", "```bash", "make -C " + study["package_path"].rstrip("/")
              + " verify", "```", "",
              f"Runs the registry's declared command and expects **{exp}**:", "",
              "```", study["verification_command"], "```", ""]
    if study.get("verification_failure_reason"):
        lines += [study["verification_failure_reason"].strip(), ""]

    lines += ["---", "",
              "Generated from [`studies/registry.yaml`](../registry.yaml), which is the only",
              "source of study state. This page adds no facts of its own; edit the registry",
              "and run `python tools/render_indexes.py`.", ""]
    return "\n".join(lines)


def package_makefile(study) -> str:
    sid = study["study_id"]
    return (f"# Verification entry point for {sid}.\n"
            "# Delegates to the command declared in studies/registry.yaml rather than\n"
            "# restating it, so a package can never disagree with the registry.\n"
            "#\n"
            "# PY is overridable and defaults to python3: `python` is absent on a stock\n"
            "# macOS PATH, and the repo venv is .venv/bin/python.\n"
            "PY ?= python3\n\n"
            ".PHONY: verify command\n\n"
            "verify:\n"
            f"\t@cd ../.. && $(PY) tools/study_verify.py {sid}\n\n"
            "command:  ## print the declared command without running it\n"
            f"\t@cd ../.. && $(PY) tools/study_verify.py {sid} --print\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    reg = load()
    targets = {ROOT / "studies/README.md": studies_index(reg),
               ROOT / "papers/README.md": papers_index(reg)}
    for study in reg["studies"]:
        pkg = study.get("package_path")
        if not pkg:
            continue
        targets[ROOT / pkg / "README.md"] = package_readme(study, reg)
        targets[ROOT / pkg / "Makefile"] = package_makefile(study)
    stale = []
    for path, content in targets.items():
        if args.check:
            current = path.read_text() if path.is_file() else ""
            if current != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("ERROR stale generated index: " + ", ".join(stale))
        print("      run: python tools/render_indexes.py")
        return 1
    if args.check:
        print("generated indexes are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
